# Generated by Django 4.0.8 on 2025-02-25 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimeTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('uploaded_csv', models.FileField(upload_to='')),
                ('generated_timetable_csv', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'exam_timetable',
            },
        ),
        migrations.CreateModel(
            name='SchoolTimeTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjects_csv', models.FileField(upload_to='')),
                ('teachers_data_csv', models.FileField(upload_to='')),
                ('generated_timetable_csv', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'school_timetable',
            },
        ),
    ]
